AWSTemplateFormatVersion: '2010-09-09'
Description: cf tutorial stack
Parameters:
  ServiceName:
    Type: String
    Description: Service Name

  Environment:
    Type: String

  KeyName:
    Type: String
    Description: EC2 access key name

Resources:
#------------------------------------------#
#SecurityGroup
#------------------------------------------#
  PublicWebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${ServiceName}-${Environment}-public-web-sg
      GroupDescription: public web server security group
      VpcId:
        Fn::ImportValue:
          !Sub ${ServiceName}-${Environment}-vpcid
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub ${ServiceName}-${Environment}-public-web-sg

  #------------------------------------------#
  #EC2 Instance
  #------------------------------------------#
  WebServerInstance:
    Type: AWS::EC2::Instance
    Metadata:
      Comment: Install a simple PHP application
      AWS::CloudFormation::Init:
        config:
          packages:
            yum:
              httpd: []
              php: []
          files:
            /var/www/html/index.php:
              content: !Sub
              |
                <?php
                echo '<h1>ENV: ${ServiceName}-${Environment}<h1>';
                ?>
              mode: '000644'
              owner: apache
              group: apache
            /etc/cfn/cfn-hup.conf:
              content: !Sub |
                [main]
                stack=${AWS::StackId}
                region=${AWS::Region}
              mode: '000400'
              owner: root
              group: root
            /etc/cfn/hooks.d/cfn-auto-reloader.conf:
              content: !Sub |
                [cfn-auto-reloader-hook]
                triggers=post.update
                path=Resources.WebServerInstance.Metadata.AWS::CloudFormation::Init
                action=/opt/aws/bin/cfn-init -s ${AWS::StackId} -r WebServerInstance --region ${AWS::Region}
                runas=root
          services:
            sysvinit:
              httpd:
                enabled: 'true'
                ensureRunning: 'true'
              cfn-hup:
                enabled: 'true'
                ensureRunning: 'true'
                files:
                  - /etc/cfn/cfn-hup.conf
                  - /etc/cfn/hooks.d/cfn-auto-reloader.conf
    Properties:
      SubnetId:
        Fn::ImportValue:
          !Sub ${NetworkStackName}-public-subnet-1a
      ImageId: ami-0f9ae750e8274075b
      InstanceType: t3.nano
      KeyName: !Sub ${KeyName}
      SecurityGroupIds:
        - !Ref PublicWebServerSecurityGroup
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 8
            VolumeType: gp2
      UserData:
        Fn::Base64:
          !Sub |
          #!/bin/sh -ex
          yum install -y aws-cfn-bootstrap
          # Install the files and packages from the metadata
          /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource WebServerInstance --region ${AWS::Region}
          # Start up the cfn-hup daemon to listen for changes to the Web Server metadata
          /opt/aws/bin/cfn-hup || error_exit ''Failed to start cfn-hup''
          # Signal the status from cfn-init
          /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource WebServerInstance --region ${AWS::Region}
      Tags:
        - Key: Name
          Value: !Sub ${ServiceName}-${Environment}-web-server
    CreationPolicy:
      ResourceSignal:
        Timeout: PT5M

