AWSTemplateFormatVersion: '2010-09-09'
Description: cf tutorial stack
Parameters:
  ServiceName:
    Type: String
    Description: Service Name

  Environment:
    Type: String

  KeyName:
    Type: String
    Description: EC2 access key name

Resources:

#------------------------------------------#
#AutoScaling::LaunchConfiguration
#------------------------------------------#
  PublicWebServerLaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      AssociatePublicIpAddress: true
      ImageId: ami-0f9ae750e8274075b
      InstanceType: t3.nano
      KeyName: !Sub ${KeyName}
      LaunchConfigurationName: !Sub ${ServiceName}-${Environment}-public-web-service
      SecurityGroups:
        - Fn::ImportValue:
            !Sub ${ServiceName}-${Environment}-web-security-group
      UserData:
        Fn::Base64:
          !Sub |
          #!/bin/sh -ex
          yum update -y
          yum install -y httpd

#------------------------------------------#
#AutoScaling
#------------------------------------------#
  PublicWebServerAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: PublicWebService
      VPCZoneIdentifier:
        - Fn::ImportValue:
            !Sub ${ServiceName}-${Environment}-public-subnet-1a
        - Fn::ImportValue:
            !Sub ${ServiceName}-${Environment}-public-subnet-1c
      DesiredCapacity: 1
      HealthCheckType: EC2
      LaunchConfigurationName: !Ref PublicWebServerLaunchConfiguration
      MaxSize: 2
      MinSize: 1
      Tags:
        - Key: Name
          Value: !Sub ${ServiceName}-${Environment}-public-web-service
          PropagateAtLaunch: true