AWSTemplateFormatVersion: 2010-09-09
Description: cloudformation tutorial stack
Parameters:
  ServiceName:
    Type: AWS::SSM::Parameter::Value<String>

  Environment:
    Type: AWS::SSM::Parameter::Value<String>

Resources:
  #------------------------------------------#
  #VPC
  #------------------------------------------#
  TutorailVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub ${ServiceName}-${Environment}-vpc
        - Key: サービス名
          Value: !Sub ${ServiceName}
        - Key: 環境
          Value: !Sub ${Environment}

  #------------------------------------------#
  #IGW
  #------------------------------------------#
  InternetGatewaty:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${ServiceName}-${Environment}-igw
        - Key: サービス名
          Value: !Sub ${ServiceName}
        - Key: 環境
          Value: !Sub ${Environment}

  AttachGatewaty:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGatewaty
      VpcId: !Ref TutorailVPC

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    DependsOn: AttachGatewaty
    Properties:
      VpcId: !Ref TutorailVPC
      Tags:
        - Key: Name
          Value: !Sub ${ServiceName}-${Environment}-routetable
        - Key: サービス名
          Value: !Sub ${ServiceName}
        - Key: 環境
          Value: !Sub ${Environment}

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGatewaty
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGatewaty

  #------------------------------------------#
  #Public Subnet
  #------------------------------------------#
  PublicSubnet1a:
    Type: AWS::EC2::Subnet
    DependsOn: AttachGatewaty
    Properties:
      AvailabilityZone: ap-northeast-1a
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      VpcId: !Ref TutorailVPC
      Tags:
        - Key: Name
          Value: !Sub ${ServiceName}-${Environment}-public-subnet-1a
        - Key: サービス名
          Value: !Sub ${ServiceName}
        - Key: 環境
          Value: !Sub ${Environment}

  PublicSubnetRouteTableAssociation1a:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1a
      RouteTableId: !Ref PublicRouteTable

  PublicSubnet1c:
    Type: AWS::EC2::Subnet
    DependsOn: AttachGatewaty
    Properties:
      AvailabilityZone: ap-northeast-1c
      CidrBlock: 10.0.2.0/24
      MapPublicIpOnLaunch: true
      VpcId: !Ref TutorailVPC
      Tags:
        - Key: Name
          Value: !Sub ${ServiceName}-${Environment}-public-subnet-1c
        - Key: サービス名
          Value: !Sub ${ServiceName}
        - Key: 環境
          Value: !Sub ${Environment}

  PublicSubnetRouteTableAssociation1c:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1c
      RouteTableId: !Ref PublicRouteTable

  #------------------------------------------#
  #Private Subnet
  #------------------------------------------#
  PrivateSubnet1a:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-northeast-1a
      CidrBlock: 10.0.11.0/24
      VpcId: !Ref TutorailVPC
      Tags:
        - Key: Name
          Value: !Sub ${ServiceName}-${Environment}-private-subnet-1a
        - Key: サービス名
          Value: !Sub ${ServiceName}
        - Key: 環境
          Value: !Sub ${Environment}

  PrivateSubnet1c:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-northeast-1c
      CidrBlock: 10.0.12.0/24
      VpcId: !Ref TutorailVPC
      Tags:
        - Key: Name
          Value: !Sub ${ServiceName}-${Environment}-private-subnet-1c
        - Key: サービス名
          Value: !Sub ${ServiceName}
        - Key: 環境
          Value: !Sub ${Environment}

Outputs:
  VPCId:
    Description: VPC ID
    Value: !Ref TutorailVPC
    Export:
      Name: !Sub ${ServiceName}-${Environment}-vpcid

  PublicSubnet1a:
    Description: The subnet ID use for public on ap-northeast-1a
    Value: !Ref PublicSubnet1a
    Export:
      Name: !Sub ${ServiceName}-${Environment}-public-subnet-1a

  PublicSubnet1c:
    Description: The subnet ID use for public on ap-northeast-1c
    Value: !Ref PublicSubnet1c
    Export:
      Name: !Sub ${ServiceName}-${Environment}-public-subnet-1c

  PrivateSubnet1a:
    Description: The subnet ID use for private on ap-northeast-1a
    Value: !Ref PrivateSubnet1a
    Export:
      Name: !Sub ${ServiceName}-${Environment}-private-subnet-1a

  PrivateSubnet1c:
    Description: The subnet ID use for private on ap-northeast-1c
    Value: !Ref PrivateSubnet1c
    Export:
      Name: !Sub ${ServiceName}-${Environment}-private-subnet-1c

