AWSTemplateFormatVersion: '2010-09-09'
Description: cfn tutorial dynamodb stack
Parameters:
  ServiceName:
    Type: AWS::SSM::Parameter::Value<String>

  Environment:
    Type: AWS::SSM::Parameter::Value<String>

Resources:
  DynamodbTutorialTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${ServiceName}-${Environment}-Usertable
      AttributeDefinitions:
        - AttributeName: UserID
          AttributeType: S
      KeySchema:
        - AttributeName: UserID
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST